### PR TITLE
Allow Pydantic v2 in test environments

### PR DESCRIPTION
**Pull request by mattwthompson**
- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/_tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
Will wait to finish this until `openff-nagl` 0.3.0 is released

**Comment by mattwthompson** [comment]
Seems to working, modulo QCArchive allowing records to be pulled down

**Review by j-wags — COMMENTED** [review]
This PR seems to do 6 things:
1. Adds pydantic=1 and 2 variants to the CI matrix
2. (maybe) Changes some things to make pydantic 2 work
3. Changes some things to make mypy happy
4. Has pre-commit start removing blank lines at ends of files
5. Makes some helpful-looking changes to `Molecule.visualize` tests
6. Gets `has_pkg` and `requires_pkg` from openff-utils instead of keeping a redundant definition

For 1 - The changes here seem to have made the test configurations more complex/brittle. What form would the final CI changes take if this is merged?

For 2 - Are there any source code changes in here to get pydantic 2 compatibility or did we have that all along?

The changes for items 3, 4, 5, and 6 are good by me.

**Comment by mattwthompson** [comment]
The toolkit does not use Pydantic at all; the objective here is to ensure tests pass with both v1 and v2. No code changes (here) are needed to allow users to install v2.

The main complexity added here is working around QCArchive not supporting v2. I don't take dropping QCArchive interoperability or limiting Pydantic compatibility to be workable options, and as long as v1 is still supported at installation time it's something that should be tested. So the final matrix will look a little more complex, with maybe a couple of combinations stripped out.

**Comment by j-wags** [comment]
Gotcha. Ok, it's great to know that OFFTK is ready for pydantic v2. I'd like to leave this open until the pydantic v2-compatible QCF packages are out. If we merge it sooner, we have no choice but to expand the cost/complexity of our CI matrix, and then make a second round of changes once the new QCF packages come out. 

If we want to allow pydantic=2 in our conda packages before then, I'd approve a PR/patch to do so!

**Comment by mattwthompson** [comment]
Seems like we already do https://prefix.dev/channels/conda-forge/packages/openff-toolkit-base

**Pull request closed without merging**
