### PR TITLE
Remove `openff.toolkit.typing.chemistry`

### PR DESCRIPTION
**Pull request by mattwthompson**
#1500, I looked through #1472 to find the changes that need to actually be removed. Grepping around for `typing.chemistry` or ` ChemicalEnvironment` don't trigger anything non-historical as far as I can tell.

- [x] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [x] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

### CODE REVIEW

**Comment by j-wags** [comment]
This would [break ForceBalance](https://github.com/leeping/forcebalance/blob/10b9280cab9735634d25a4f9c8b3e84cb13a6bb1/src/smirnoff_hack.py#L76). It should be possible to remove the validate cache from ForceBalance entirely since it is no longer used and then move forward with this. 

@jthorton @cringrose94 @bieniekmateusz  This will [affect and probably break QUBEKit](https://github.com/qubekit/QUBEKit/blob/01165ef1ef14f2f74847c54aa4219e538b9ce68a/qubekit/torsions/utils.py#L27). It looks like you missed the deprecation warning because QUBEKit never instantiates a `ChemicalEnvironment` object but rather somehow calls `validate` as a classmethod. I'm thinking you could either remove the line and skip validation or copy `environment.py` to QUBEKit.

**Comment by jthorton** [comment]
Thanks for the warning @j-wags, Ill look into changing this!

**Review by j-wags — APPROVED** [review]
This one is going to require a bit of pinning in our ecosystem for a while, but it's really important to me that we keep all of the deprecation followthroughs in the 0.14.0 release, so merging this now is the lesser of two evils.

**Comment by j-wags** [comment]
After thinking some more, in the interest of not teaching the new science team hires to downpin their envs on their first day, I'm gonna revert this so we can get the other API deprecations out. We include these changes in an off-schedule API breaking release once ForceBalance is ready for this.

**Pull request merged**
