### PR TITLE
docs: updated docs for SMIRNOFF spec around AMBER/GROMACS

### PR DESCRIPTION
**Pull request by ethanholz**
Updated to reference the new notebook instead of the older one. Related to https://github.com/openforcefield/standards/issues/66.

- [x] Tag issue being addressed https://github.com/openforcefield/standards/issues/66
- [ ] ~~Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/_tests)~~
- [ ] ~~Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable~~
- [ ] ~~[Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase~~
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

What would I need to do to update the changelog?

### CODE REVIEW

**Review by j-wags — APPROVED** [review]
Thanks @ethanholz, please update the changelog before merging. To update the changelog you have to ignore broken link in the PR template and instead add a line under `Current Development` in the [hidden REAL changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.md) 🤦 

(If you'd like more github fame and glory, feel free to fix the PR template to have the correct changelog link in either this or a subsequent PR... Otherwise I'll take care of it in due time)

**Comment by ethanholz** [comment]
No worries! I have in fact already had the change for that merged at #1880 so we are already good to go there!

**Comment by ethanholz** [comment]
I have updated the releasehistory with the change for these docs in the following commit: [95037be](https://github.com/openforcefield/openff-toolkit/pull/1878/commits/95037be325a7404aff06e0697c88a10933cf94ff).

**Comment by j-wags** [comment]
Excellent. The failing OpenEye tests are expected. This is ready for merge - Are you able to click the merge button or do the failing tests prevent you? (this whole PRs-from-forks thing is driving me crazy this morning haha)

**Comment by mattwthompson** [comment]
@ethanholz I've invited you to the org (Jeff can revert this if I'm overstepping a boundary here). The UI game me this

> You've invited Ethan Holz to Open Force Field Initiative! They'll be receiving an email shortly. They can also visit https://github.com/openforcefield to accept the invitation.

**Pull request merged**
