### PR TITLE
Rework externally-dependent examples into dedicated subdirectory

### PR DESCRIPTION
**Pull request by mattwthompson**
Closes most of [these](https://github.com/openforcefield/openff-toolkit/issues?q=is%3Aissue+is%3Aopen+parmed) issues.

A summary of the changes in this PR:
- [x] Make a new folder `examples/external` in order to communicate that some examples rely on external tools that may break without our doing but to fill in key functionality gaps in our current products, with a README that can be improved upon in future PRs
- [x] `examples/swap_amber_parameters` -> `examples/external/swap_amber_parameters`
- [x] Remove `examples/using_smirnoff_in_amber_or_gromacs/convert_with_parmed.ipynb`
- [x] Add `examples/using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb`
- [x] Update `examples/using_smirnoff_with_amber_protein_forcefield/` notebooks to not use ParmEd
- [x] Update examples environments to not use `bioconda` channel
- [x] Use `openff-amber-ff-ports >=0.0.3`  https://github.com/openforcefield/amber-ff-porting/pull/40 /  https://github.com/openforcefield/openff-amber-ff-ports/pull/5
- [x] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by j-wags** [comment]
I spoke with @Yoshanuikabundi about this and he agrees that it's a complex choice. In the end, we decided that @Yoshanuikabundi should refactor the toolkit showcase to not use ParmEd or OpenMMForceFields, and that it should stay outside the `external` folder. He'll do that in a separate PR, so could you leave the toolkit showcase unchanged in this PR, @mattwthompson?

**Comment by mattwthompson** [comment]
```shell
$ grep -rl parmed examples
examples/toolkit_showcase/toolkit_showcase.ipynb
examples/external/swap_amber_parameters/swap_existing_ligand_parameters.ipynb
examples/external/swap_amber_parameters/README.md
examples/external/swap_existing_ligand_parameters_with_openmmforcefields.ipynb
examples/deprecated/testing/test_system_conversion/convert_to_amber.ipynb
examples/deprecated/mixedFF_structure/README.md
examples/deprecated/mixedFF_structure/generate_mixedFF_complex.py
$ grep -rl openmmforcefields examples
examples/toolkit_showcase/toolkit_showcase.ipynb
examples/environment.yaml
examples/external/swap_amber_parameters/README.md
examples/external/swap_existing_ligand_parameters_with_openmmforcefields.ipynb

**Comment by mattwthompson** [comment]
This is ready for review and at this point I would advocate for merging it as-is; there are plenty of improvements to be had here but this has already been open for too long and includes too many changes for one PR. More changes can always be added before a new release, up to and including adding release blockers as a condition of merging this.

I've also updated the original post of this PR to include a condensed summary of changes. Debt incurred in the past year or so of some examples being turned off is not repaid, but it is at least noted clearly.

**Review by j-wags — APPROVED** [review]
Thanks for all your patience on this. I really like the idea of fully removing parmed from our recommendations, but until we have any other way of suggesting how someone could take a externally-parameterized component and mix it with OpenFF-parameterized components, we should keep a version of one of these notebooks around that shows how to do that with ParmEd. So this is good to merge pending two changes:

* toluene_in_t4 has an error in saved output - We should either clear the output (if it doesn't have useful info anyway) or rerun it without the error output
* Refactoring both examples in `using_smirnoff_with_amber_protein_forcefield/` effectively leaves us with no recommendation for any pathways to mix OpenFF-parameterized components with externally-parameterized components. The parmed pathway is messy but we should keep an example around until Interchange importers can offer an alternative. So let's add a copy of the original `examples/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb` into the `external/` folder.

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
