### PR TITLE
Update for Pint 0.20

### PR DESCRIPTION
**Pull request by mattwthompson**
Ref https://github.com/openforcefield/openff-units/pull/51

### CODE REVIEW

**Comment by mattwthompson** [comment]
This it totally fine in the original PR but is totally broken when used outside of the package itself.

**Comment by mattwthompson** [comment]
We actually will need a PR into this toolkit with this update. It can be this PR with most of the debug code stripped out, but I don't want to remove it until I make a new `openff-units` release.

In loading a force field, `object_to_quantity` sends SMIRKS patterns to Pint and if some error was thrown, it just accepted the string as-is. Now a `pint.DefinitionSyntaxError` is thrown, which for some reason was not caught in the existing `except` block.

**Comment by mattwthompson** [comment]
The examples are failing because QCEngine has not been updated, though that it in the works. I think it would be unwise to wait for that before merging and releasing these changes.

**Review by j-wags — APPROVED** [review]
LGTM! Thanks for digging in.

**Pull request merged**
