### PR TITLE
Re-run cookbooks

### PR DESCRIPTION
**Pull request by mattwthompson**
The cookbooks are consistently failing in CI and I'm not sure why ... I re-ran them locally with `nbconvert` and also captured an expected error as text to avoid returning an exit code.

### CODE REVIEW

**Comment by mattwthompson** [comment]
This will take more digging (or somebody who is more familiar with this particular location)

```
Run pytest -v --no-cov --durations=5 --nbval --ignore docs/_build/ docs/
  pytest -v --no-cov --durations=5 --nbval --ignore docs/_build/ docs/
  shell: /usr/bin/bash -l {0}
  env:
    OE_LICENSE: /home/runner/work/openff-toolkit/openff-toolkit/oe_license.txt
    PACKAGE: openff
    PYTEST_ARGS: -r fE --tb=short -nauto
    COV: --cov=openff/toolkit --cov-config=setup.cfg --cov-append --cov-report=xml
    ENVFILE: test_env
    JOBNAME: RDKit and OpenEye
    TOOLKIT_CHECKS: RDKIT OPENEYE
    PACKAGES_TO_REMOVE: 
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
============================= test session starts ==============================
platform linux -- Python 3.9.18, pytest-8.0.0, pluggy-1.4.0 -- /home/runner/micromamba/envs/openff-toolkit-test/bin/python3.9
cachedir: .pytest_cache
rootdir: /home/runner/work/openff-toolkit/openff-toolkit
configfile: setup.cfg
plugins: xdist-3.5.0, cov-4.1.0, rerunfailures-13.0, nbval-0.10.0
collecting ... collected 31 items

docs/users/molecule_cookbook::ipynb::Cell 0 FAILED                       [  3%]
docs/users/molecule_cookbook::ipynb::Cell 1 PASSED                       [  6%]
docs/users/molecule_cookbook::ipynb::Cell [2](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:2) PASSED                       [  9%]
docs/users/molecule_cookbook::ipynb::Cell [3](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:3) PASSED                       [ 12%]
docs/users/molecule_cookbook::ipynb::Cell [4](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:4) PASSED                       [ 16%]
docs/users/molecule_cookbook::ipynb::Cell [5](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:5) PASSED                       [ 19%]
docs/users/molecule_cookbook::ipynb::Cell [6](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:6) PASSED                       [ 22%]
docs/users/molecule_cookbook::ipynb::Cell [7](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:7) PASSED                       [ 25%]
docs/users/molecule_cookbook::ipynb::Cell [8](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:8) PASSED                       [ 2[9](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:9)%]
docs/users/molecule_cookbook::ipynb::Cell 9 PASSED                       [ 32%]
docs/users/molecule_cookbook::ipynb::Cell [10](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:10) PASSED                      [ 35%]
docs/users/molecule_cookbook::ipynb::Cell [11](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:11) PASSED                      [ 38%]
docs/users/molecule_cookbook::ipynb::Cell [12](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:12) PASSED                      [ 41%]
docs/users/molecule_cookbook::ipynb::Cell [13](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:13) PASSED                      [ 45%]
docs/users/molecule_cookbook::ipynb::Cell [14](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:14) PASSED                      [ 48%]
docs/users/molecule_cookbook::ipynb::Cell [15](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:15) PASSED                      [ 51%]
docs/users/molecule_cookbook::ipynb::Cell [16](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:17) PASSED                      [ 54%]
docs/users/molecule_cookbook::ipynb::Cell [17](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:18) PASSED                      [ 58%]
docs/users/molecule_cookbook::ipynb::Cell [18](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:19) PASSED                      [ 61%]
docs/users/molecule_cookbook::ipynb::Cell [19](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:20) PASSED                      [ 64%]
docs/users/molecule_cookbook::ipynb::Cell [20](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:21) PASSED                      [ 67%]
docs/users/molecule_cookbook::ipynb::Cell [21](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:22) PASSED                      [ 70%]
docs/users/molecule_cookbook::ipynb::Cell [22](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:23) PASSED                      [ 74%]
docs/users/molecule_cookbook::ipynb::Cell [23](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:24) PASSED                      [ 77%]
docs/users/molecule_cookbook::ipynb::Cell [24](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:25) PASSED                      [ 80%]
docs/users/pdb_cookbook/index::ipynb::Cell 0 PASSED                      [ 83%]
docs/users/pdb_cookbook/index::ipynb::Cell 1 PASSED                      [ 87%]
docs/users/pdb_cookbook/index::ipynb::Cell 2 PASSED                      [ 90%]
docs/users/pdb_cookbook/index::ipynb::Cell 3 PASSED                      [ 93%]
docs/users/pdb_cookbook/index::ipynb::Cell 4 PASSED                      [ 96%]
docs/users/pdb_cookbook/index::ipynb::Cell 5 PASSED                      [100%]

=================================== FAILURES ===================================
__________________ docs/users/molecule_cookbook.ipynb::Cell 0 __________________
Notebook cell execution failed
Cell 0: Cell outputs differ

Input:
# Workaround for https://github.com/conda-forge/qcfractal-feedstock/issues/43
try:
    import qcportal  # noqa
except ImportError:
    pass

import sys

ipython = get_ipython()  # noqa


def hide_traceback(
    exc_tuple=None,
    filename=None,
    tb_offset=None,
    exception_only=False,
    running_compiled_code=False,
):
    """Hide tracebacks for simpler errors."""
    etype, value, _ = sys.exc_info()
    value.__cause__ = None  # suppress chained exceptions
    return ipython._showtraceback(
        etype,
        value,
        ipython.InteractiveTB.get_exception_only(etype, value),
    )


ipython.showtraceback = hide_traceback

# Hide NumPy warnings
import warnings

warnings.filterwarnings(
    "ignore",
    r"The value of the smallest subnormal for ",
)

Traceback:
Unexpected output fields from running code: {'stderr'}

============================= slowest 5 durations ==============================
45.12s call     docs/users/pdb_cookbook/index.ipynb::Cell 4
15.78s call     docs/users/pdb_cookbook/index.ipynb::Cell 2
11.82s call     docs/users/pdb_cookbook/index.ipynb::Cell 3
7.61s call     docs/users/pdb_cookbook/index.ipynb::Cell 1
6.81s call     docs/users/molecule_cookbook.ipynb::Cell 14
=========================== short test summary info ============================
FAILED docs/users/molecule_cookbook.ipynb::Cell 0
=================== 1 failed, [30](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:31) passed in 95.97s (0:01:[35](https://github.com/openforcefield/openff-toolkit/actions/runs/7748589247/job/21131478456#step:18:36)) ====================

**Comment by j-wags** [comment]
Huh, thanks for taking a look at this. It pains me to say it, but since this is cosmetic I'd be in favor of going ahead with the release today and then I'll dig into this afterwards.

**Comment by mattwthompson** [comment]
The problem is that re-running the notebooks doesn't seem to fix anything

**Comment by mattwthompson** [comment]
For posterity the ❌ results from a bug in which OEChem thought a license expiring in April 2024 actually expires on January 30, 2024. It'd still be nice to re-run these notebooks once in a while, but that's a separate thread from what got me started here.

**Pull request closed without merging**
