### PR TITLE
Fix PDB writing from `OpenEyeToolkitWrapper`

### LINKED ISSUE #845: PDBs written using OpenEyeToolkitWrapper don't contain atom names from OFFMol
**Describe the bug**

```
from openforcefield.topology import Molecule
from openforcefield.utils.toolkits import RDKitToolkitWrapper, OpenEyeToolkitWrapper
mol = Molecule.from_smiles('CCO')
mol.generate_unique_atom_names()
mol.to_file('test_oetkw.pdb', file_format='pdb', toolkit_registry=OpenEyeToolkitWrapper())
```

yields a pdb file without unique atom names
```
ATOM      1  C   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      2  C   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      3  O   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      4  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      5  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      6  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      7  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      8  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
ATOM      9  H   UNL     1       0.000   0.000   0.000  0.00  0.00 
CONECT    1    2    4    5    6
CONECT    2    3    7    8
CONECT    3    9
END
```
If we use RDKitToolkitWrapper, 
```
mol.to_file('test_rdtkwk.pdb', file_format='pdb', toolkit_registry=RDKitToolkitWrapper())
```
we DO get a file with unique atom names
```
HETATM    1  C1  UNL     1       0.000   0.000   0.000  1.00  0.00           C  
HETATM    2  C2  UNL     1       0.000   0.000   0.000  1.00  0.00           C  
HETATM    3  O1  UNL     1       0.000   0.000   0.000  1.00  0.00           O  
HETATM    4  H1  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
HETATM    5  H2  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
HETATM    6  H3  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
HETATM    7  H4  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
HETATM    8  H5  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
HETATM    9  H6  UNL     1       0.000   0.000   0.000  1.00  0.00           H  
CONECT    1    2    4    5    6
CONECT    2    3    7    8
CONECT    3    9
END
```

**Computing environment (please complete the following information):**
 - Mac OSX
```
openeye-toolkits          2020.1.0                 py37_0    openeye
openforcefield            0.8.0+129.g3c1663f1.dirty           dev_0    <develop>
```

**Additional context**
I've emailed OpenEye about this, will update the issue when I head back.

### LINKED ISSUE #1307: `OpenEyeToolkitWrapper.to_file` writes PDB files with no CONECT records
**Describe the bug**
A `Molecule` written to a PDB file **includes** CONECT records when OpenEye Toolkits are **not** available but **excludes** them when they **are**. This can lead to surprising results - or at least I did not expect the choice of toolkit backend to have this effect.

**To Reproduce**

```python3
from openff.toolkit import Molecule
from openff.toolkit.utils.toolkits import (
    OpenEyeToolkitWrapper,
    RDKitToolkitWrapper,
    ToolkitRegistry,
)

molecule = Molecule.from_smiles("CC(=O)NC1=CC=C(C=C1)O")
molecule.generate_conformers(n_conformers=1)

molecule.to_file("via_openeye.pdb", "PDB", ToolkitRegistry([OpenEyeToolkitWrapper()]))
molecule.to_file("via_rdkit.pdb", "PDB", ToolkitRegistry([RDKitToolkitWrapper()]))
```

**Output**

```shell
$ python pdb_issue.py
$ wc -l *pdb
      22 via_openeye.pdb
      31 via_rdkit.pdb
      53 total
$ cat via_openeye.pdb
ATOM      0  C   UNL     1       1.405  -0.654  -3.811  1.00 20.00
ATOM      0  C   UNL     1       0.989  -0.470  -2.373  1.00 20.00
ATOM      0  O   UNL     1      -0.059   0.102  -2.091  1.00 20.00
ATOM      0  N   UNL     1       1.928  -1.015  -1.507  1.00 20.00
ATOM      0  C   UNL     1       1.885  -1.036  -0.112  1.00 20.00
ATOM      0  C   UNL     1       2.921  -1.631   0.608  1.00 20.00
ATOM      0  C   UNL     1       2.878  -1.652   2.002  1.00 20.00
ATOM      0  C   UNL     1       1.800  -1.079   2.676  1.00 20.00
ATOM      0  C   UNL     1       0.764  -0.484   1.955  1.00 20.00
ATOM      0  C   UNL     1       0.807  -0.463   0.561  1.00 20.00
ATOM      0  O   UNL     1       1.756  -1.102   4.036  1.00 20.00
ATOM      0  H   UNL     1       2.007   0.201  -4.134  1.00 20.00
ATOM      0  H   UNL     1       0.518  -0.724  -4.447  1.00 20.00
ATOM      0  H   UNL     1       1.989  -1.573  -3.916  1.00 20.00
ATOM      0  H   UNL     1       2.741  -1.450  -1.939  1.00 20.00
ATOM      0  H   UNL     1       3.767  -2.080   0.093  1.00 20.00
ATOM      0  H   UNL     1       3.688  -2.117   2.558  1.00 20.00
ATOM      0  H   UNL     1      -0.079  -0.036   2.474  1.00 20.00
ATOM      0  H   UNL     1      -0.006   0.003   0.010  1.00 20.00
ATOM      0  H   UNL     1       2.542  -1.549   4.390  1.00 20.00
TER       1      UNL     1
END
$ cat via_rdkit.pdb
HETATM    1  C1  UNL     1       1.405  -0.654  -3.811  1.00  0.00           C
HETATM    2  C2  UNL     1       0.989  -0.470  -2.373  1.00  0.00           C
HETATM    3  O1  UNL     1      -0.059   0.102  -2.091  1.00  0.00           O
HETATM    4  N1  UNL     1       1.928  -1.015  -1.507  1.00  0.00           N
HETATM    5  C3  UNL     1       1.885  -1.036  -0.112  1.00  0.00           C
HETATM    6  C4  UNL     1       2.921  -1.631   0.608  1.00  0.00           C
HETATM    7  C5  UNL     1       2.878  -1.652   2.002  1.00  0.00           C
HETATM    8  C6  UNL     1       1.800  -1.079   2.676  1.00  0.00           C
HETATM    9  C7  UNL     1       0.764  -0.484   1.955  1.00  0.00           C
HETATM   10  C8  UNL     1       0.807  -0.463   0.561  1.00  0.00           C
HETATM   11  O2  UNL     1       1.756  -1.102   4.036  1.00  0.00           O
HETATM   12  H1  UNL     1       2.007   0.201  -4.134  1.00  0.00           H
HETATM   13  H2  UNL     1       0.518  -0.724  -4.447  1.00  0.00           H
HETATM   14  H3  UNL     1       1.989  -1.573  -3.916  1.00  0.00           H
HETATM   15  H4  UNL     1       2.741  -1.450  -1.939  1.00  0.00           H
HETATM   16  H5  UNL     1       3.767  -2.080   0.093  1.00  0.00           H
HETATM   17  H6  UNL     1       3.688  -2.117   2.558  1.00  0.00           H
HETATM   18  H7  UNL     1      -0.079  -0.036   2.474  1.00  0.00           H
HETATM   19  H8  UNL     1      -0.006   0.003   0.010  1.00  0.00           H
HETATM   20  H9  UNL     1       2.542  -1.549   4.390  1.00  0.00           H
CONECT    1    2   12   13   14
CONECT    2    3    3    4
CONECT    4    5   15
CONECT    5    6   10   10
CONECT    6    7    7   16
CONECT    7    8   17
CONECT    8    9    9   11
CONECT    9   10   18
CONECT   10   19
CONECT   11   20
END
```

**Computing environment (please complete the following information):**
```
pip install git+https://github.com/openforcefield/openff-toolkit.git@topology-biopolymer-refactor
```

probably pointing to commit 57a442b5c4403016df8770ca3dca64c5cb8bbc0a. I originally found this using #1276 but reproduced it on each branch.

**Additional context**

I didn't look too deeply into the root causes, test other molecules, etc., it can surely be reproduced with something simpler. I'm ripping this almost directly from an Evaluator unit test that is failing because of this (later, an MDTraj `Topology` lacks bonds where it's expected to have them, and I was able to trace this back to the toolkit writing the PDB file that MDTraj read back.)

I can never keep track of what the expected behavior with CONECT records is in the cacophony of ways they can come into existence. If there **are** any reliable expectations we do have, I'd be happy to write them up in documentation and and add some unit tests to ensure the right behavior (and that the behavior does not surprisingly vary with backend toolkit).

### PR DESCRIPTION
**Pull request by mattwthompson**
Follow-on from #848 by @j-wags 

- [ ] Ensure atom ordering is not changed in unexpected ways (https://github.com/openforcefield/openff-toolkit/pull/848#issuecomment-1144955309)
- [x] Fix #845
- [x] Fix #1307 
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
This seems to fix #1307:

```shell
$ python pdb_issue.py && wc -l *pdb
      32 via_openeye.pdb
      31 via_rdkit.pdb
      63 total
```

(the difference is a TER line, which I don't think is that big of a deal)

**Comment by mattwthompson** [comment]
I'm pretty stumped by the atom ordering issue. Letting OpenEye re-order atoms in a manner that's inconsistent with the original molecule is too much of a breaking change for me to swallow. Even before considering the vs. RDKit differences. Unfortunately this means the dead-simple fix to #1307 and #845 (just call `OEPerceiveResidues` and fix the atom names later) would introduce a regression by re-introducing #475.

The unit test created a water with atom ordering "HOH", which is re-ordered to "OHH" when `OEPerceiveResidues` is called. I thought this could possibly be due to perceiving the water as a residue (crazier things have happened), but I re-wrote it to be an "HNHH" ammonia molecule and the same behavior (reordered to "NHHH") occurs.

The same thing happens with a molecule that's more obviously drug-like (there's no way acetaminophen could be perceived to be a standard residue, right?):

```python3
In [27]: oemol = Molecule.from_smiles("C1CC2=C3C(=CC=C2)C(=CN3C1)[C@H]4[C@@H](C(=O)NC4=O)C5=CNC6=CC=CC=C65").to_openeye
    ...: ()

In [28]: original = [oeatom.GetAtomicNum() for oeatom in oemol.GetAtoms()]

In [29]: oechem.OEPerceiveResidues(oemol)

In [30]: for original_atomic_number, new_atomic_number in zip(original, [oeatom.GetAtomicNum() for oeatom in oemol.GetA
    ...: toms()]):
    ...:     print(original_atomic_number, new_atomic_number, '###' if original_atomic_number != new_atomic_number else
    ...:  '')
    ...:
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
6 6
7 7
6 6
6 6
1 6 ###
6 6
1 8 ###
6 7 ###
8 6 ###
7 8 ###
6 6
8 6 ###
6 7 ###
6 6
7 6 ###
6 6
6 6
6 6
6 6
6 1 ###
6 1 ###
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1

**Comment by j-wags** [comment]
> Letting OpenEye re-order atoms in a manner that's inconsistent with the original molecule is too much of a breaking change for me to swallow

Agreed. We can't reorder atoms on write, that's a big regression and not worth it. Thanks for taking a deep dive into this, I think we should close this PR, label the bugs as high effort, and contact OE again when we have time.

**Comment by mattwthompson** [comment]
Should we leave #1307 as buggy behavior? The alternative would be turning off OpenEye-based PDB writing of non-residues or emitting a warning that the `CONECT` records of previous versions might not be there.

**Comment by j-wags** [comment]
OpenMM's PDB writing functionality is pretty nice Could evaluator's internal code path use that instead of OpenEyeToolkitWrapper?

**Pull request closed without merging**
