### PR TITLE
Fix CI, update examples

### PR DESCRIPTION
**Pull request by mattwthompson**
- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

### CODE REVIEW

**Comment by j-wags** [comment]
I'd poked around the failing charge tests this weekend - I think the Quantities in `numpy.allclose` just need to be unwrapped (`value_in_unit`? `m_as`?) but I could remember how to do that in Pint.

**Comment by mattwthompson** [comment]
That should be the fix, but I couldn't reproduce it locally, so I pushed the version constraints to see if that magically fixed it (of course it didn't)

**Comment by mattwthompson** [comment]
This is not great

```
2023-05-09T04:36:15.0301221Z Installing collected packages: openff-toolkit
2023-05-09T04:36:15.4094481Z ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
2023-05-09T04:36:15.4095812Z Successfully installed openff-toolkit-0+untagged.3.g4ce1f64
2023-05-09T04:36:15.4097148Z openff-nagl 0+unknown requires rdkit, which is not installed.

**Comment by mattwthompson** [comment]
Tricky

```python
ipdb> assert numpy.allclose([1, 2] * unit.elementary_charge, [1, 2] * unit.eleme
ntary_charge)
ipdb> assert numpy.allclose([1, 2] * unit.elementary_charge, [1, 2] * unit.eleme
ntary_charge, atol=1e-3)
*** pint.errors.DimensionalityError: Cannot convert from 'dimensionless' to 'elementary_charge'
ipdb> assert numpy.allclose([1, 2] * unit.elementary_charge, [1, 2] * unit.eleme
ntary_charge, atol=1e-3 * unit.elementary_charge)

**Review by j-wags — APPROVED** [review]
Ahh, good sleuthing!

**Comment by mattwthompson** [comment]
Thanks! I added a note explaining (and disclaiming the risks of) `%env INTERCHANGE_EXPERIMENTAL=1`, which I forgot to do earlier.

**Pull request merged**
