### PR TITLE
Ensure NonbondedForce cutoff is set to vdW handler's cutoff

### LINKED ISSUE #734: VdW Cutoff Ignored when Electrostatic Handler Present
**Describe the bug**
The non-bonded cutoff is hardcoded in several places (the [`vdWHandler`](https://github.com/openforcefield/openforcefield/blob/7091de5daf03abfa487e7c3619eafcfcbff91d1d/openforcefield/typing/engines/smirnoff/parameters.py#L3226) and the [`ElectrostaticsHandler`](https://github.com/openforcefield/openforcefield/blob/7091de5daf03abfa487e7c3619eafcfcbff91d1d/openforcefield/typing/engines/smirnoff/parameters.py#L3524)). This hardcoded value overwrites the value set by both the `vdWHandler` and the `ElectrostaticsHandler`.

**To Reproduce**

```
# Create a dummy topology containing only argon and give it a set of
# box vectors.
topology = Molecule.from_smiles("[Ar]").to_topology()
topology.box_vectors = numpy.eye(3) * unit.nanometers

# Create the FF
force_field = ForceField()

# Add only a VdW handler.
vdw_handler = vdWHandler(version=0.3)
vdw_handler.method = "cutoff"
vdw_handler.cutoff = 6.0 * unit.angstrom
vdw_handler.scale14 = 1.0

vdw_handler.add_parameter(
    {
        "smirks": "[#18:1]",
        "epsilon": 1.0 * unit.kilojoules_per_mole,
        "sigma": 1.0 * unit.angstrom
    }
)

force_field.register_parameter_handler(vdw_handler)

# Map the FF to the dummy topology
system = force_field.create_openmm_system(topology)

assert numpy.isclose(
    system.getForce(0).getCutoffDistance().value_in_unit(unit.angstrom),
    6.0
)

# Add an electrostatics handler.
electrostatics_handler = ElectrostaticsHandler(version=0.3)
electrostatics_handler.cutoff = 6.0 * unit.angstrom
electrostatics_handler.method = "PME"
force_field.register_parameter_handler(electrostatics_handler)

library_charges = LibraryChargeHandler(version=0.3)
library_charges.add_parameter(
    {
        "smirks": "[#18:1]",
        "charge1": 0.0 * unit.elementary_charge,
    }
)
force_field.register_parameter_handler(library_charges)

system = force_field.create_openmm_system(topology)

assert numpy.isclose(
    system.getForce(0).getCutoffDistance().value_in_unit(unit.angstrom),
    6.0
)
```

**Output**

```AssertionError``` on the final assert.

**Computing environment (please complete the following information):**
 - `openforcefield = 0.7.2`

### PR DESCRIPTION
**Pull request by mattwthompson**
Fixes #734 

I was working on bigger changes but wanted to make this (relatively) small patch first. I think the best approach is to forcefully fix this in the final steps of `create_openmm_system`.  Until we finish #914,  cutoffs can't be mismatched at all,, except for the case of cutoff vdW and PME electrostatics in which the PME "cutoff" isn't particularly meaningful anyway.

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
No clue why everything is passing given #886 is still open

**Review by j-wags — COMMENTED** [review]
Do we have an authoritative reference for the statement "If the NonbondedForce is using the `PME` method, then the cutoff set on the NonbondedForce is used for vdW, but a different cutoff is used for the electrostatics PME short-range/long range transition"? 

At [one point in the docs](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.NonbondedForce.html#simtk.openmm.openmm.NonbondedForce.setEwaldErrorTolerance), it's implied that the ewald error tolerance is used to determine the cutoff between the regions, but I'd like to make sure that this is the case. 

Otherwise this PR looks good, I just remember scratching my head about nonbonded methods about a year ago, and I think writing this stuff down now can save us time in the future.

**Comment by mattwthompson** [comment]
> At one point in the docs, it's implied that the ewald error tolerance is used to determine the cutoff between the regions, but I'd like to make sure that this is the case.

I agree with your assessment here and actually came across the same text while half-reading your comment at first. ~~Still, I couldn't find a definitive answer myself, although some threads in the OpenMM issue tracker imply that either some PME tuning happens by default or the PME "cutoff" is not the same as `.getCutoffDistance().~~ However, I did find an ancient thread that points to a thoroughly-commented script, which includes this comment that somewhat specifically answers our question.

> The nonbonded cutoff does not affect the accuracy of the Coulomb interaction with PME.  You can
    freely vary the cutoff distance, and OpenMM will automatically select internal parameters to give
    whatever accuracy has been selected with the ewaldErrorTolerance parameter.  (The cutoff does affect
    other nonbonded interactions, such as Lennard-Jones, so this generally places a lower limit on the
    cutoffs you consider acceptable.)


https://github.com/openmm/openmm/issues/55

https://simtk.org/svn/pyopenmm/trunk/simtk/pyopenmm/extras/optimizepme.py

It _seems_ like there is no on-the-fly PME tuning that happens at runtime like what happens in GROMACS, but that's not the same as asking  "is the vdW cutoff the same distance used to switch electrostatics interactions from real space to reciprocal space?" For a few years I've been operating on the assumption that the PME "cutoff" is an implementation detail that can significantly impact performance but (if everything is set up correctly) shouldn't damage results.

I think it's reasonable to say that if we're both confused, this is an area of the OpenMM docs that could be improved.

**Comment by j-wags** [comment]
So based on the discussion in the openMM issue, it seems like PME cutoff DOES change the boundary between direct-space and reciprocal-space electrostatics, but it doesn't matter, and PME cutoff shouldn't be part of the SMIRNOFF spec. 

I'll work on figuring out what that means for this PR. And also the spec, I guess.

**Review by j-wags — APPROVED** [review]
Thanks for all the thinking on this, @mattwthompson, and sorry it's taken me so long to get to it. These changes look good. 

This PR allows something that was previously unallowed, but I think that the SMIRNOFF spec will have to eventually change to be more specific about how the different cutoffs should be treated. At that time, I think there will be a different set of configuration options ADDED for PME electrostatics, and the cutoff will take on a different meaning than is used here. So I don't think that merging this now is likely to paint us into a reverse-incompatibility corner in the future. 

Could you update the releasenotes before you merge? Thanks!

**Pull request merged**
