### PR TITLE
Add Molecule.smirnoff_impropers and .amber_impropers

### LINKED ISSUE #746: Make `offmol.smirnoff_impropers` and `offmol.single_impropers`
**Describe the bug**
Not really a bug, possibly naive question about intended behavior in enumerating indices for improper torsions.

I was surprised at the large number of torsions included in `offmol.impropers` for some molecules (e.g. `len(methane.impropers) == 24`).

[The way `offmol.impropers` are enumerated](https://github.com/openforcefield/openforcefield/blob/ce77ebafc29eccd53c3fba4ea011a750d2a2ef81/openforcefield/topology/molecule.py#L4798-L4838) appears maximally permissive, in that it doesn't place a constraint on the connectivity or identity of the central atom (except that it must have connectivity of >= 3). I think it's equivalent to returning all chemical environment matches for the SMARTS pattern `"[*:1]~[*:2](~[*:3])~[*:4]"` ("a central atom and 3 tagged neighbors").

Are there other constraints we wish to impose on the indices returned by `offmol.impropers`? For example, would it be desirable to impose a constraint that the connectivity of the central atom is _exactly_ 3 (`"[*:1]~[X3:2](~[*:3])~[*:4]"` )?

**To Reproduce**
```python
from openforcefield.topology import Molecule

improper_smarts = "[*:1]~[X3:2](~[*:3])~[*:4]"
#permissive_improper_smarts = "[*:1]~[*:2](~[*:3])~[*:4]"

smiles_list = ["C", "N", "CCCCC", 'C'*1000]

def compare_improper_enumeration_schemes(smiles):
    offmol = Molecule.from_smiles(smiles)

    smarts_inds = offmol.chemical_environment_matches(improper_smarts)
    offmol_inds = [tuple([atom.molecule_atom_index for atom in improper]) for improper in offmol.impropers]

    print(f'smiles:\n\t{smiles}')
    print(f'matches for substructure search "{improper_smarts}":\n\t{len(smarts_inds)}')
    print(f'offmol.impropers:\n\t{len(offmol_inds)}')
    print(f'set(smarts_matches) is subset of set(offmol.impropers):\n\t{set(smarts_inds).issubset(offmol_inds)}\n\n')

for smiles in smiles_list:
    compare_improper_enumeration_schemes(smiles)
```

**Output**
```
smiles:
	C
matches for substructure search "[*:1]~[X3:2](~[*:3])~[*:4]":
	0
offmol.impropers:
	24
set(smarts_matches) is subset of set(offmol.impropers):
	True


smiles:
	N
matches for substructure search "[*:1]~[X3:2](~[*:3])~[*:4]":
	6
offmol.impropers:
	6
set(smarts_matches) is subset of set(offmol.impropers):
	True


smiles:
	CCCCC
matches for substructure search "[*:1]~[X3:2](~[*:3])~[*:4]":
	0
offmol.impropers:
	120
set(smarts_matches) is subset of set(offmol.impropers):
	True


smiles:
	CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
matches for substructure search "[*:1]~[X3:2](~[*:3])~[*:4]":
	0
offmol.impropers:
	24000
set(smarts_matches) is subset of set(offmol.impropers):
	True
```

**Computing environment:**
`openforcefield==0.7.1`

### PR DESCRIPTION
**Pull request by mattwthompson**
Resolves #746, in particular the spec described in https://github.com/openforcefield/openforcefield/issues/746#issuecomment-710574144

- [x] Add `Topology` and `TopologyMolecule.smirnoff_impropers` and `amber_impropers`
- [ ] More test cases? Does adding other molecules i.e. benzene add anything? What about other potentially nasty chemistries?
- [ ] Worth adding `n_smirnoff_impropers`/`n_amber_impropers`?
- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
The iterables of valences in `Molecule` (`_impropers`, `_torsions`, etc.) are stored and returned as sets (or, more speciflcally, set of tuples of `Atom`s). This causes potential issues when ordering matters. Say a molecule has the same impropers following each definition ("all possible", SMIRNOFF, and Amber-style). The ordering of each does not match up with the others, i.e. the Nth torsion in `molecule.impropers` is almost guaranteed to be different than `molecule.smirnoff_impropers` for no other reason than they are stored as sets instead of lists. By necessity, I've made them lists for the new properties, but I would also like to move the others over to lists. I think they're only guaranteed to act as iterables, and if anybody is already relying on the order of a returned set, that seems dangerous.

**Comment by jchodera** [comment]
> I think they're only guaranteed to act as iterables, and if anybody is already relying on the order of a returned set, that seems dangerous.

+1 that nobody should be relying on the ordering here.

**Comment by jchodera** [comment]
Is this feature slated for a release milestone? Just checking for our purposes in [espaloma](https://github.com/choderalab/espaloma).

cc @yuanqing-wang

**Comment by mattwthompson** [comment]
Look for it in 0.8.3, loosely slated for sometime next month

**Comment by jchodera** [comment]
Thanks!

**Review by j-wags — APPROVED** [review]
Thanks, Matt. Impropers are complicated so I've beefed up the docstrings to indicate that these may not correspond 1:1 with physics terms, and added some potential to-dos. In the future, we may want to avoid using cheminformatics toolkits at all, since finding trivalent centers can just be done by iterating over all atoms and finding those with three bonds. But we can wait for a user request for that. Merging!

**Comment by mattwthompson** [comment]
Thanks for getting this one finished up!

**Pull request merged**
