### PR TITLE
Lazy load networkx

### PR DESCRIPTION
**Pull request by mattwthompson**
Whenever `Molecule` is imported , `import networkx as nx` is also called, whether or not it is needed for functionality. It's one of the slower imports, so I lazy-loading it can save ~0.15 seconds of import time in what I presume is a significant number of our users' workflows.

Before:
image

After:
image

- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by adalke** [comment]
I'm all for deferred imports to improve initial import cost and skip importing when not needed.

In this case, I think your code path is deferring a bit too much. Every other code path will end up importing networkx, eg, by calling a `obj.to_networkx()` method.

The only performance advantage you'll get is if the input isn't one of the support types, and doesn't have a `__class__.__name__` matching "Graph". Which isn't going to be often enough to optimize.

My suggestion is to move the:
```
import networkx as nx
```
to the top of 
```
def to_networkx(data):
```

This also means the error message won't be different for the "Graph-object-but-not-a-networkx-Graph" case, but I don't think that's something to have.

**Comment by mattwthompson** [comment]
That does seem quite a bit better; the diff here is simpler than I thought  it was going to be and I don't remember why this change wasn't already in place. I did some import profiling a few months back but maybe I didn't see that idea to completion ...

**Comment by Lnaden** [comment]
Not something I have direct experience with but have been thinking of adding to a few projects is the built in `importlib.util.LazyLoader` which has been in since 3.5: 

https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader

That way you don't have to have `import` statements in a bunch of functions. Its a bit tricky to setup and use though: https://stackoverflow.com/questions/42703908/how-do-i-use-importlib-lazyloader

Not sure how helpful this is, but something to consider.

**Review by adalke — APPROVED** [review]
Looks good.

**Review by j-wags — APPROVED** [review]
Agreed! This looks good to me too. Thanks, @mattwthompson!

**Comment by mattwthompson** [comment]
Thanks!

**Pull request merged**
