### PR TITLE
Enable new OpenFF theme

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
We broke the theme out into its own [repository.](https://github.com/openforcefield/openff-sphinx-theme/) This PR serves as a test of the changes required to enable the new theme.

- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Review by j-wags — APPROVED** [review]
I really like the look of this. There are a few areas of the docs, like in the SMIRNOFF spec, where this has really improved the readability. I'll go ahead and approve this now, but I think we should get @SimonBoothroyd (on vacation until next week) and @mattwthompson to check this out for their repos and approve it before we apply it across all our docs.

**Comment by mattwthompson** [comment]
Is this live, or will it not be propagated until a release is cut? I poked around in the "Versions" tab but didn't get anywhere

https://open-forcefield-toolkit.readthedocs.io/en/latest/

**Comment by Yoshanuikabundi** [comment]
Good catch. Looks like `latest` on RTD is stuck on commit 7c3dfbae - probably because of the [`latest` tag](https://github.com/openforcefield/openff-toolkit/releases/tag/latest) that we set up to support [Binder caching](https://github.com/openforcefield/openff-toolkit/issues/286#issuecomment-825655553), which hasn't been updated for new releases. I'll report this as a bug to RTD, as RTD's `latest` is [supposed](https://docs.readthedocs.io/en/stable/versions.html) to point to `master`.

**Comment by Yoshanuikabundi** [comment]
@mattwthompson Ok, the theme now renders correctly on RTD!

https://open-forcefield-toolkit.readthedocs.io/en/latest/

The problems we had, for posterity:
 - The `latest` version pointed to the `latest` tag, which was an undocumented RTD behaviour. So we renamed our `latest` tag to `stable` in #1068
 - RTD builds the `latex` target as well as the `html` target, and this uncovered a bug in the theme where CSS and HTML post-processing steps failed on targets that didn't need them. I just fixed this bug, and I'll set up CI for the theme to avoid regressions.

I'm kinda glad we did this on the Toolkit first now, because I had the permissions I needed to iterate quickly 😅 Any, everything should work now!

**Comment by mattwthompson** [comment]
Looks great!

**Pull request merged**
