### PR TITLE
General polymer implementation with existing from_pdb and rdkit wrapper

### PR DESCRIPTION
**Pull request by connordavel**
More info and simple write-up/motivation can be found [here](https://docs.google.com/document/d/1LB1-9RpNWJ-R6wlNjJer5vlFB_LF2cNUhD9xS5QKq-c/edit). This PR adds custom substructure functionality to allow Users to modify the substructure dictionary and load custom polymers, functionalized proteins, or protein/polymer systems. 

Checklist:
- [X] Input Handling for custom substructures and integration with existing substructure dictionary
- [X] Error handling for ambiguous chemical assignments from custom substructures. If custom substructures disagree with eachother or the existing library, raise exception
- [x] input validation for custom substructures that adhere to the following general string format: "...-[#<atomic num>D<explicit connect>+<formal charge>]-..."
- [x] simple testing on a few simple polymers and modified protein
- [x] testing to ensure input validation and exceptions

A short testing script with examples can be found [here.](https://github.com/connordavel/Minimum-Polymer-Tests)

### CODE REVIEW

**Comment by j-wags** [comment]
Thanks for your patience while I scrambled around for the annual meeting. I've looked over this a bit today. This looks extremely promising! 

I was really excited to see your tests repo, especially `messy_sugar.pdb` (though I later saw that this one is still out of reach... I think sugars will be a stretch goal for a while). The tests repo overall looks great though, and your minimum cases are exactly what I was looking for :-) 

Knowing that you're heading out for the summer and grad school soon, we don't need to put the burden of finishing this on you - What'd help a lot here would be to get the overall content/skeleton on here, and then I can work on cleanups, documentation, and integrating tests. Off the top of my head, two things that would really help would be if you could:

* Meet with me briefly to migrate this PR to a branch of the Toolkit instead of your personal fork (this will allow the entire continuous integration testing suite to run)
* Add your new code for generating the protein substructures - this should overwrite the stuff in `utilities/make_substructure_dict`

Thanks a million for working so hard on this. I know you're preparing a paper as well so I'll try to stay out of your hair as much as I can.

**Comment by mrshirts** [comment]
@connordavel can speak more for himself, but the next month or so will probably be the best time to sync on things - he's still doing some paid work for the group, so can do some of the documentation and testing.  After that, he will be off doing other things.  So take advantage of time  now!

I think we can do sugars, we'll generate some slightly less messy ones :)

**Comment by connordavel** [comment]
Thanks for taking a look at this. I'll be putting together a few more tests (especially involving systems with weird ligands and amino acids from the protein databank hopefully) that will double as results for the paper. That should give a good basis for further work when I'm off to school again. I'll also be quite free this week to meet so I'll message you about that as well.

**Comment by j-wags** [comment]
This has been retargeted to a feature branch of the right repo so we can get OE tests to run. So this is good to merge, and we can continue work on this branch moving forward.

**Pull request merged**
