### PR TITLE
[DNM] Test against Interchange development head

### PR DESCRIPTION
**Pull request by mattwthompson**
- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

### CODE REVIEW

**Review by j-wags — APPROVED** [review]
Thanks - This looks good. I'll wait to merge this until the production Interchange 0.3.0 release. But for now I'll downpin interchange in the OFFTK package recipe to remove the ticking clock element here.

**Comment by j-wags** [comment]
Seeing some local test failures with GBSA, though I'm not convinced that the issue isn't with my dev environment or how the tests are set up. I'll work on isolating the problem tomorrow and will open an issue on Interchange if I think it's there.

**Comment by mattwthompson** [comment]
The most recent test failures are due to something failing while unpacking FreeSolv files and therefore not finding some MOL2 files needed for tests, but only on macOS. I have not investigated the cause of these failures. Given that the tests pass on the Linux jobs, I am comfortable assuming that it's a configuration error in tests and not a genuine OS-specific behavior differences in the code.

**Comment by j-wags** [comment]
Hooray! Test failures seem unrelated. Thanks for kicking this CI.

**Pull request closed without merging**
