### PR TITLE
Allow int-based virtual site parameter lookup

### LINKED ISSUE #1893: Virtual site parameter lookups don't support safe indexing
In #1861 while disallowing SMIRKS-based lookups I also removed support for int-based indexing into the parameter list, which I don't think should be considered unsafe.

```python
In [1]: from openff.toolkit import ForceField

In [2]: ForceField("opc.offxml")['VirtualSites'].parameters[0]
/Users/mattthompson/micromamba/envs/openff-interchange-env/lib/python3.11/site-packages/smirnoff99frosst/smirnoff99frosst.py:11: UserWarning: Module openff was already imported from None, but /Users/mattthompson/software/openff-interchange is being added to sys.path
  from pkg_resources import resource_filename
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 ForceField("opc.offxml")['VirtualSites'].parameters[0]

File ~/micromamba/envs/openff-interchange-env/lib/python3.11/site-packages/openff/toolkit/typing/engines/smirnoff/parameters.py:1614, in VirtualSiteParameterList.__getitem__(self, val)
   1613 def __getitem__(self, val):
-> 1614     raise NotImplementedError(
   1615         "VirtualSiteHandler does not support __getitem__ lookups due to the "
   1616         "number of values required to uniquely identify a specific parameter."
   1617     )

NotImplementedError: VirtualSiteHandler does not support __getitem__ lookups due to the number of values required to uniquely identify a specific parameter.
```

### PR DESCRIPTION
**Pull request by mattwthompson**
Fixes #1893 

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/_tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.md)

### CODE REVIEW

**Review by j-wags — APPROVED** [review]
Looks great, please update releasenotes before you merge. This seems important so I'm happy to cut a release any time.

**Comment by mattwthompson** [comment]
A release would be nice, non-essential. I've only used the patterns in tests, but it may have percolated out into examples or industry code somewhere. So having 0.16.1 be the most recent version for a shorter period of time would help a little.

**Comment by j-wags** [comment]
Feel free to merge with failing RTD - That's on my plate to fix and shouldn't delay this.

**Comment by mattwthompson** [comment]
Oof ... I feel like I saw that last week but it's been coming and going. Fun!

**Pull request merged**
