### PR TITLE
Raise exception when processing molecule with radical electrons

### PR DESCRIPTION
**Pull request by mattwthompson**
Here's a block to add to the changelog, keeping it out of the tree to make merges easier:

```
- [PR #1236](https://github.com/openforcefield/openff-toolkit/pull/1236) raises
  [`RadicalsNotSupportedError`](openff.toolkit.utils.exceptions.RadicalsNotSupportedError) when
  [`Molecule.from_openeye`](openff.toolkit.topology.Molecule.from_openeye),
  [`Molecule.from_rdkit`](openff.toolkit.topology.Molecule.from_rdkit),
  [`Molecule.from_smiles`](openff.toolkit.topology.Molecule.from_smiles), or similar methods
  detect that a molecule contains radical electrons.
```

Resolves https://github.com/openforcefield/openff-toolkit/issues/1075, assuming I haven't forgotten how chemistry works.

This is a follow-on to #1098 targeting the v0.11.x line.

Two remaining considerations may be:
* Performance evaluation - this adds an O(number of atoms) check to two key conversion methods.
* False positives - I have no idea if this will be too noisy and claim to have found radicals where none exist. Throwing this at a large dataset should give an indication of this.

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [x] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
Some InChi roundtrips are showing different behavior; I don't know if that's good or bad.

I've added a milestone for 0.11.1 because this is **not a requirement** for the 0.11.0 release.

**Comment by j-wags** [comment]
I'll look into these test failures, but to recap a statement I just made in a synchronous meeting with @mattwthompson:

There are three outcomes to a user loading a molecule with a radical into OFFTK:
1) The molecule could be loaded with a cheminformatics toolkit "fixing" the radical by adding an H
2) The user could get an error
3) The user could get an OFFMol with a radical

Right now, trying to parameterize neutral CH3 gets us errors from quacpac and antechamber, so that's clearly an invalid input for our infrastructure. `CCCC[S+]` emitted an antechamber warning, but succeeded in parameterization and resulted in all-0 partial charges (!).

So, I'm coming around to the idea of totally forbidding radicals for now in the toolkit, at least until we have defined behavior specified, and we establish that we explicitly DO aim to have those in scope.

**Comment by j-wags** [comment]
Allllright, I think this should be fixed throughout but I'll wait for tests to pass before running a final review. Minidrugbank is such an awful test set, maybe things are finally quiet enough that I can sit down and make a new one.

**Comment by mattwthompson** [comment]
Humor shows up in unexpected places:

```
=================================== FAILURES ===================================
_ examples/check_dataset_parameter_coverage/check_parameter_coverage.ipynb::Cell 2 _
Notebook cell execution failed
Cell 2: Cell execution caused an exception

Input:
molecules = Molecule.from_file("example_molecules.smi", allow_undefined_stereo=True)

# We also provide a SMILES dataset of ~1000 problematic molecules
# molecules =  Molecule.from_file('problem_smiles.smi', allow_undefined_stereo=True)

print(f"Loaded {len(molecules)} molecules")

Traceback:

---------------------------------------------------------------------------
RadicalsNotSupportedError                 Traceback (most recent call last)
Cell In [4], line 1
----> 1 molecules = Molecule.from_file("example_molecules.smi",allow_undefined_stereo=True)
      3 # We also provide a SMILES dataset of ~1000 problematic molecules
      4 # molecules =  Molecule.from_file('problem_smiles.smi', allow_undefined_stereo=True)
      6 print(f"Loaded {len(molecules)} molecules")

**Comment by j-wags** [comment]
> Humor shows up in unexpected places:

Laughing it up all the way to the deprecated folder. I don't feel like rewriting a large fraction of that notebook, and it was largely a early marketing tool to show groups "hey look, we COULD parameterize your molecules". We have more impressive things to show off now.

**Pull request merged**
