### PR TITLE
Fix requires_openeye_mol2 decorator

### LINKED ISSUE #874: Tests requiring OpenEye's MOL2 parser are not running.
**Describe the bug**
I believe that in #615 I introduced a bug that surprisingly skips a large portion of the test suite. I don't believe this  directly leaks over to the core API, but there could be issues resulting from tests skipping for the last while.

This heavily affects some of the tests that run through large datasets, at very least the FreeSolve file(s).

**To Reproduce**

The core of the behavior is here:

https://github.com/openforcefield/openff-toolkit/blob/1a201f16abbc27bbeec858ec840481e749a6f08c/openff/toolkit/tests/utils.py#L45-L51

You'd expect these decorators to be identical, since you'd expect passing one arg to the other work. But `.args` returns a tuple, which results in weird behavior. Here is a minimally reproducing cases with no toolkit code:

```
import pytest

do_not_skip = pytest.mark.skipif(False, reason="")
chained_mark = pytest.mark.skipif(do_not_skip.args, reason="")

@do_not_skip
def test_should_run():
    assert True
# PASSED


@chained_mark
def test_should_also_run():
    assert True
# SKIPPED
```

and back to the toolkit code: chaining marks resulted in a nest tuple.
```python3
In [1]: from openff.toolkit.tests.utils import requires_openeye_mol2, requires_openeye

In [2]: requires_openeye.args
Out[2]: (False,)

In [3]: requires_openeye_mol2.args
Out[3]: ((False,),)
```

So, this **should** be a small fix, incoming in a moment.

**Output**
A zillion skipped tests when running the test suite, either locally on or CI. Can quickly reproduce via `pytest openff/toolkit/tests/test_forcefield.py::TestForceFieldParameterAssignment::test_alkethoh_parameters_assignment` on the current `master` branch; this is a single test that has the `@requires_openeye_mol2` decorator. On two machines, and probably all of CI, this test is completely skipped (and probably has for months).

**Additional context**
Ideally we can trim away the number of intentionally-skipped tests so that thousands more tests skipping as a result of one of my patches does not go undetected.

### PR DESCRIPTION
**Pull request by mattwthompson**
Fixes #874, may or may not uncover other test failures

- [x] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/master/openff/toolkit/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/master/docs/releasehistory.rst)

### CODE REVIEW

**Comment by mattwthompson** [comment]
I'm getting a few failures locally when throwing in the `--runslow` flag (since a lot of the FreeSolv data is tagged as slow). @j-wags I will let you decide if we should merge this as-is and fix potential issues in a follow-up or do them both here.

**Comment by j-wags** [comment]
Hm, yeah, I'm able to reproduce some failures locally too.

```
=================================== short test summary info ===================================
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1199854-0_0_2-False-HCT-False]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1199854-0_0_2-False-OBC2-False]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[129464-0_0_2-False-HCT-True]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1328936-0_0_2-False-OBC1-True]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1328936-0_0_2-False-OBC2-True]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1424265-0_0_2-False-OBC1-False]
FAILED test_forcefield.py::TestForceFieldParameterAssignment::test_freesolv_gbsa_energies[1563176-0_0_2-False-OBC1-True]
```

An example error is

```
utils.py:491: FailedEnergyComparisonError
_ TestForceFieldParameterAssignment.test_freesolv_gbsa_energies[1563176-0_0_2-False-OBC1-True] _

self = <toolkit.tests.test_forcefield.TestForceFieldParameterAssignment object at 0x155024820>
gbsa_model = 'OBC1', is_periodic = True, freesolv_id = '1563176', forcefield_version = '0_0_2'
allow_undefined_stereo = False
...

E           openff.toolkit.tests.utils.FailedEnergyComparisonError: potential energy 1 0.2602185114625156 kJ/mol, potential energy 2: 0.26021088207088344 kJ/mol

utils.py:491: FailedEnergyComparisonError

```

Fixing/dismissing these errors is beyond the scope of this PR, so I think this is good to merge.

**Review by j-wags — APPROVED** [review]
LGTM! Sorry for the delay.

**Comment by mattwthompson** [comment]
It looks like this didn't actually fix it? The [merge](https://github.com/openforcefield/openff-toolkit/commit/3c05a06d81ec0ccf36c82df966db90b6caea1559) commit has roughly 10,000 skipped tests and even [runs](https://github.com/openforcefield/openff-toolkit/actions/runs/688236607) on this PR are also skipping?

**Pull request merged**
