### PR TITLE
Fix docs builds

### PR DESCRIPTION
**Pull request by mattwthompson**
Starting grasping at straws

https://pip.pypa.io/en/stable/news/#v23-2

### CODE REVIEW

**Comment by mattwthompson** [comment]
That ... worked?

**Comment by mattwthompson** [comment]
If I'm not missing anything, I think this is good to go.

Pinning to an old version of `pip` is not good, but our docs not being build it not good-er.

**Comment by j-wags** [comment]
I redid the "stable" pin assignment in the 0.14.2 release around the same time as you opened this PR - I've reverted the changes to kick CI so we can tease apart whether this was the effective fix.

**Comment by j-wags** [comment]
Looks like the RTD build ran with no changes. Thanks for hopping on this so quickly, but I think it was doing the new release and stable-tag-setting correctly that got RTD back.

**Pull request closed without merging**
