### PR TITLE
Central examples

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
This PR includes example refreshments in anticipation of the new examples page (https://github.com/openforcefield/openff-docs/pull/7)

- [ ] SMIRNOFF_simulation/run_simulation.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] using_smirnoff_with_amber_protein_forcefield/toluene_in_T4_lysozyme.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [ ] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [ ] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] external/swap_existing_ligand_parameters_with_openmmforcefields/swap_existing_ligand_parameters_with_openmmforcefields.ipynb (previously external/swap_amber_parameters/swap_existing_ligand_parameters_with_openmmforcefields.ipynb)
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [ ] Ensure there's prose
    - [x] Thumbnail
    - [x] Category
- [ ] external/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [x] external/swap_amber_parameters/swap_existing_ligand_parameters.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [x] Thumbnail
    - [x] Category
- [ ] using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] inspect_assigned_parameters/inspect_assigned_parameters.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [x] conformer_energies/conformer_energies.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [x] Thumbnail
    - [x] Category
- [ ] virtual_sites/vsite_showcase.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [ ] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] QCArchive_interface/QCarchive_interface.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [ ] Ensure there's prose
    - [ ] Thumbnail
    - [ ] Category
- [ ] toolkit_showcase/toolkit_showcase.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [ ] visualization/visualization.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [ ] Thumbnail
    - [x] Category
- [x] forcefield_modification/forcefield_modification.ipynb
    - [x] Check/fix title
    - [x] Remove installation instructions
    - [x] Ensure there's prose
    - [x] Thumbnail
    - [x] Category
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
We should talk about deprecating several of these:

 - `conformer_energies` is very similar to the same notebook in Interchange, and it's arguably done better there even after the refresh I gave it here
 - `using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb` is definitely done better in Interchange
 - SMIRNOFF_simulation/run_simulation.ipynb, using_smirnoff_with_amber_protein_forcefield/toluene_in_T4_lysozyme.ipynb, using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb, and using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb all seem redundant with the Toolkit Showcase, though maybe less so after Rosemary comes out (because the Showcase will no longer combine Sage with Amber)
 - external/using_smirnoff_with_amber_protein_forcefield/BRD4_inhibitor_benchmark.ipynb and external/swap_amber_parameters/swap_existing_ligand_parameters.ipynb seem redundant - both are "combine sage and amber with ParmEd". I think these might have been more different in the past.

Some of these seem like they'd be useful integration tests even if they'd clutter the examples list - `using_smirnoff_in_amber_or_gromacs/export_with_interchange.ipynb` for instance. Maybe we can mark them hidden or hide them in a folder that we still test but don't render?

**Comment by j-wags** [comment]
Could you deprecate the T4 lysozyme "combining FFs" example?

**Review by j-wags — COMMENTED** [review]
I'll take care of the remaining changes on here so @Yoshanuikabundi can focus on finishing up the openff-docs example rendering.
* Update the conformer energies python script in line with the notebook updates
* Double check changed prose+titles in all examples to make sure they have the correct meaning.

**Review by j-wags — APPROVED** [review]
Fantastic - Thanks @Yoshanuikabundi. I'll merge once tests pass!

**Pull request merged**
